"""withdrawal cases

Revision ID: 00964d94889f
Revises: 724d58724a23
Create Date: 2026-09-16 14:30:25.306311
"""
from alembic import op
import sqlalchemy as sa


revision = '00964d94889f'
down_revision = '724d58724a23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=20), server_default='payment', nullable=False))
        batch_op.add_column(sa.Column('withdrawal_id', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_cases_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_withdrawal_id'), ['withdrawal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_withdrawal_id'))
        batch_op.drop_index(batch_op.f('ix_cases_kind'))
        batch_op.drop_column('withdrawal_id')
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
