"""drop_authorized_users

Revision ID: 0afe0c6f4826
Revises: 59bfff8d7108
Create Date: 2026-09-11 12:24:53.091166
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0afe0c6f4826'
down_revision = '59bfff8d7108'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorized_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorized_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('telegram_user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('authorized_users_pkey')),
    sa.UniqueConstraint('role', 'telegram_user_id', name=op.f('uq_authorized_role_uid'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
