"""mobile as primary identifier

Revision ID: 1547a5cbd7f3
Revises: 69d2748fa255
Create Date: 2026-09-10 15:57:03.551801
"""

import sqlalchemy as sa
from alembic import op

revision = "1547a5cbd7f3"
down_revision = "69d2748fa255"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mobile", sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f("ix_cases_mobile"), ["mobile"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cases_mobile"))
        batch_op.drop_column("mobile")

    # ### end Alembic commands ###
