"""case betix order upi

Revision ID: 2b14f06d9797
Revises: 0afe0c6f4826
Create Date: 2026-09-11 13:48:29.372077
"""
from alembic import op
import sqlalchemy as sa


revision = '2b14f06d9797'
down_revision = '0afe0c6f4826'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('betix_order_upi', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('betix_order_upi')

    # ### end Alembic commands ###
