"""drop_unused_columns

Revision ID: 59bfff8d7108
Revises: 7459a7f149c0
Create Date: 2026-09-10 21:13:56.039097
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '59bfff8d7108'
down_revision = '7459a7f149c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('evidence_waived')
        batch_op.drop_column('collection_deadline')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('evidence_waived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
