"""original customer, betix anchor, confirmation attribution

Revision ID: 69d2748fa255
Revises: 9ff1a91fcd32
Create Date: 2026-09-10 15:37:54.817902
"""

import sqlalchemy as sa
from alembic import op

revision = "69d2748fa255"
down_revision = "9ff1a91fcd32"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("original_user_id", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("original_username", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("original_first_name", sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column("original_last_name", sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column("original_chat_id", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("original_message_id", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("evidence_forwarded", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("betix_chat_id", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("followup_1_message_id", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("followup_2_message_id", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("confirmation_type", sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column("confirmation_message_id", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("confirmation_user_id", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("confirmation_username", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("confirmation_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f("ix_cases_original_user_id"), ["original_user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cases_original_user_id"))
        batch_op.drop_column("confirmation_at")
        batch_op.drop_column("confirmation_username")
        batch_op.drop_column("confirmation_user_id")
        batch_op.drop_column("confirmation_message_id")
        batch_op.drop_column("confirmation_type")
        batch_op.drop_column("followup_2_message_id")
        batch_op.drop_column("followup_1_message_id")
        batch_op.drop_column("betix_chat_id")
        batch_op.drop_column("evidence_forwarded")
        batch_op.drop_column("original_message_id")
        batch_op.drop_column("original_chat_id")
        batch_op.drop_column("original_last_name")
        batch_op.drop_column("original_first_name")
        batch_op.drop_column("original_username")
        batch_op.drop_column("original_user_id")

    # ### end Alembic commands ###
