"""followup attempts

Revision ID: 724d58724a23
Revises: b361273cfb6c
Create Date: 2026-09-13 00:49:36.005141
"""
from alembic import op
import sqlalchemy as sa


revision = '724d58724a23'
down_revision = 'b361273cfb6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followups', schema=None) as batch_op:
        # server_default so the existing rows get 0; new rows take the model default
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.drop_column('attempts')

    # ### end Alembic commands ###
