"""collection_deadline

Revision ID: 7459a7f149c0
Revises: b5811a6ba2ee
Create Date: 2026-09-10 18:59:37.517448
"""

import sqlalchemy as sa
from alembic import op

revision = "7459a7f149c0"
down_revision = "b5811a6ba2ee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("collection_deadline", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_column("collection_deadline")

    # ### end Alembic commands ###
