"""case pi check orders

Revision ID: 8d3e12f4bf6c
Revises: 2b14f06d9797
Create Date: 2026-09-11 18:06:05.781358
"""
from alembic import op
import sqlalchemy as sa


revision = '8d3e12f4bf6c'
down_revision = '2b14f06d9797'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pi_check_orders', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('pi_check_orders')

    # ### end Alembic commands ###
