"""order fields on cases and candidates

Revision ID: 9ff1a91fcd32
Revises: f265d8e66c08
Create Date: 2026-09-10 15:19:22.736412
"""

import sqlalchemy as sa
from alembic import op

revision = "9ff1a91fcd32"
down_revision = "f265d8e66c08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("order_created_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("order_amount", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("gateway", sa.String(length=60), nullable=True))

    with op.batch_alter_table("order_candidates", schema=None) as batch_op:
        batch_op.add_column(sa.Column("gateway", sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column("betix_plat_order_no", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_candidates", schema=None) as batch_op:
        batch_op.drop_column("betix_plat_order_no")
        batch_op.drop_column("gateway")

    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_column("gateway")
        batch_op.drop_column("order_amount")
        batch_op.drop_column("order_created_at")

    # ### end Alembic commands ###
