"""drop case betix order upi

Revision ID: b361273cfb6c
Revises: 8d3e12f4bf6c
Create Date: 2026-09-11 22:52:15.377154
"""
from alembic import op
import sqlalchemy as sa


revision = 'b361273cfb6c'
down_revision = '8d3e12f4bf6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('betix_order_upi')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('betix_order_upi', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
