"""progress_message

Revision ID: b5811a6ba2ee
Revises: bcef20fe3f75
Create Date: 2026-09-10 17:11:28.315167
"""

import sqlalchemy as sa
from alembic import op

revision = "b5811a6ba2ee"
down_revision = "bcef20fe3f75"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("progress_chat_id", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("progress_message_id", sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_column("progress_message_id")
        batch_op.drop_column("progress_chat_id")

    # ### end Alembic commands ###
