"""evidence_waived

Revision ID: bcef20fe3f75
Revises: 1547a5cbd7f3
Create Date: 2026-09-10 17:04:12.649120
"""

import sqlalchemy as sa
from alembic import op

revision = "bcef20fe3f75"
down_revision = "1547a5cbd7f3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("evidence_waived", sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_column("evidence_waived")

    # ### end Alembic commands ###
