"""initial schema

Revision ID: f265d8e66c08
Revises:
Create Date: 2026-09-10 00:31:55.116501
"""

import sqlalchemy as sa
from alembic import op

revision = "f265d8e66c08"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=40), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("result", sa.String(length=40), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=60), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_case_id"), ["case_id"], unique=False)

    op.create_table(
        "authorized_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role", "telegram_user_id", name="uq_authorized_role_uid"),
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("source_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("source_user_id", sa.BigInteger(), nullable=False),
        sa.Column("source_username", sa.String(length=100), nullable=True),
        sa.Column("registration_number", sa.String(length=100), nullable=True),
        sa.Column("illunise_order_id", sa.String(length=100), nullable=True),
        sa.Column("betex_pay_order_id", sa.String(length=100), nullable=True),
        sa.Column("betix_plat_order_no", sa.String(length=100), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("payment_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("utr", sa.String(length=64), nullable=True),
        sa.Column("upi_id", sa.String(length=120), nullable=True),
        sa.Column("payer_name", sa.String(length=200), nullable=True),
        sa.Column("statement_password", sa.String(length=120), nullable=True),
        sa.Column("extraction", sa.JSON(), nullable=True),
        sa.Column("match_confidence", sa.Float(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("betix_posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("betix_root_message_id", sa.BigInteger(), nullable=True),
        sa.Column("system_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_by", sa.String(length=200), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("followup_cancelled", sa.Boolean(), nullable=False),
        sa.Column("followups_sent", sa.Integer(), nullable=False),
        sa.Column("last_input_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cases_betex_pay_order_id"), ["betex_pay_order_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_betix_plat_order_no"), ["betix_plat_order_no"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_case_id"), ["case_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_cases_illunise_order_id"), ["illunise_order_id"], unique=False)
        batch_op.create_index("ix_cases_open_lookup", ["source_chat_id", "status", "last_input_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_registration_number"), ["registration_number"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_source_chat_id"), ["source_chat_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_source_user_id"), ["source_user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_utr"), ["utr"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=40), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=80), nullable=False),
        sa.Column("chat_id", sa.String(length=50), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("sent", sa.Boolean(), nullable=False),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_notification_key"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_case_id"), ["case_id"], unique=False)

    op.create_table(
        "betix_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=40), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("reply_to_message_id", sa.BigInteger(), nullable=True),
        sa.Column("direction", sa.String(length=3), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=True),
        sa.Column("sender_id", sa.BigInteger(), nullable=True),
        sa.Column("sender_username", sa.String(length=100), nullable=True),
        sa.Column("sender_name", sa.String(length=200), nullable=True),
        sa.Column("sender_is_bot", sa.Boolean(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("has_media", sa.Boolean(), nullable=False),
        sa.Column("classification", sa.JSON(), nullable=True),
        sa.Column("correlation", sa.JSON(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.case_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "message_id", name="uq_betix_messages_chat_msg"),
    )
    with op.batch_alter_table("betix_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_betix_messages_case_id"), ["case_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_betix_messages_reply_to_message_id"), ["reply_to_message_id"], unique=False
        )

    op.create_table(
        "case_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=40), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.Column(
            "received_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.case_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "message_id", name="uq_case_messages_chat_msg"),
    )
    with op.batch_alter_table("case_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_case_messages_case_id"), ["case_id"], unique=False)

    op.create_table(
        "case_status_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=40), nullable=False),
        sa.Column("from_status", sa.String(length=40), nullable=True),
        sa.Column("to_status", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.case_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("case_status_history", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_case_status_history_case_id"), ["case_id"], unique=False)

    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=40), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=False),
        sa.Column("file_id", sa.String(length=300), nullable=True),
        sa.Column("file_unique_id", sa.String(length=100), nullable=True),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("filename", sa.String(length=300), nullable=True),
        sa.Column("mime_type", sa.String(length=120), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("local_path", sa.String(length=500), nullable=True),
        sa.Column("downloaded", sa.Boolean(), nullable=False),
        sa.Column("analysis", sa.JSON(), nullable=True),
        sa.Column("posted_to_betix_message_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "uploaded_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.case_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_chat_id", "telegram_message_id", name="uq_evidence_msg"),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evidence_case_id"), ["case_id"], unique=False)

    op.create_table(
        "followups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=40), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("betix_message_id", sa.BigInteger(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.case_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "number", name="uq_followup_case_number"),
    )
    with op.batch_alter_table("followups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_followups_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_followups_due_at"), ["due_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_followups_status"), ["status"], unique=False)

    op.create_table(
        "order_candidates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=40), nullable=False),
        sa.Column("search_attempt", sa.Integer(), nullable=False),
        sa.Column("illunise_order_id", sa.String(length=100), nullable=True),
        sa.Column("betex_order_id", sa.String(length=100), nullable=True),
        sa.Column("registration_number", sa.String(length=100), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("order_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=80), nullable=True),
        sa.Column("utr", sa.String(length=64), nullable=True),
        sa.Column("upi_id", sa.String(length=120), nullable=True),
        sa.Column("payer_name", sa.String(length=200), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("signals", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.case_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_candidates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_order_candidates_case_id"), ["case_id"], unique=False)

    op.create_table(
        "verification_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=40), nullable=False),
        sa.Column("dedupe_key", sa.String(length=80), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("authority", sa.String(length=30), nullable=False),
        sa.Column("betix_message_id", sa.BigInteger(), nullable=True),
        sa.Column("actor", sa.String(length=200), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.case_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "dedupe_key", name="uq_verification_event"),
    )
    with op.batch_alter_table("verification_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_verification_events_case_id"), ["case_id"], unique=False)

    op.create_table(
        "order_matches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=40), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=True),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("runner_up_confidence", sa.Float(), nullable=True),
        sa.Column("illunise_order_id", sa.String(length=100), nullable=True),
        sa.Column("betex_order_id", sa.String(length=100), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["order_candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.case_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_matches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_order_matches_case_id"), ["case_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_matches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_matches_case_id"))

    op.drop_table("order_matches")
    with op.batch_alter_table("verification_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_verification_events_case_id"))

    op.drop_table("verification_events")
    with op.batch_alter_table("order_candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_candidates_case_id"))

    op.drop_table("order_candidates")
    with op.batch_alter_table("followups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_followups_status"))
        batch_op.drop_index(batch_op.f("ix_followups_due_at"))
        batch_op.drop_index(batch_op.f("ix_followups_case_id"))

    op.drop_table("followups")
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_case_id"))

    op.drop_table("evidence")
    with op.batch_alter_table("case_status_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_case_status_history_case_id"))

    op.drop_table("case_status_history")
    with op.batch_alter_table("case_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_case_messages_case_id"))

    op.drop_table("case_messages")
    with op.batch_alter_table("betix_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_betix_messages_reply_to_message_id"))
        batch_op.drop_index(batch_op.f("ix_betix_messages_case_id"))

    op.drop_table("betix_messages")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_case_id"))

    op.drop_table("notifications")
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cases_utr"))
        batch_op.drop_index(batch_op.f("ix_cases_status"))
        batch_op.drop_index(batch_op.f("ix_cases_source_user_id"))
        batch_op.drop_index(batch_op.f("ix_cases_source_chat_id"))
        batch_op.drop_index(batch_op.f("ix_cases_registration_number"))
        batch_op.drop_index("ix_cases_open_lookup")
        batch_op.drop_index(batch_op.f("ix_cases_illunise_order_id"))
        batch_op.drop_index(batch_op.f("ix_cases_case_id"))
        batch_op.drop_index(batch_op.f("ix_cases_betix_plat_order_no"))
        batch_op.drop_index(batch_op.f("ix_cases_betex_pay_order_id"))

    op.drop_table("cases")
    op.drop_table("authorized_users")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_case_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    # ### end Alembic commands ###
